version: '3.1'
services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: academy
      POSTGRES_PASSWORD: academy
      POSTGRES_DB: electricity
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
  fastapi_app:
    build: .
    container_name: fastapi_server
    depends_on:
      - db
    environment:
      POSTGRES_USER: academy
      POSTGRES_PASSWORD: academy
    ports:
      - "8000:8000"